### ISSUE TITLE
When can we have a api doc?

### ISSUE THREAD

**Issue by liuziw** [HamaWhiteGG/langchain-java#102]
When can we have a api doc?

**Comment by HamaWhiteGG** [comment]
next week， i will finish it

**Comment by HamaWhiteGG** [comment]
Yes, I finish it. 
Use maven-javadoc-plugin to generate and push docs to [gh-pages](https://github.com/HamaWhiteGG/langchain-java/tree/gh-pages) branch .
This will be automatically executed via GitHub Actions when merging code into the main branch.

API doc index: https://hamawhitegg.github.io/langchain-java

langchain-core doc: https://hamawhitegg.github.io/langchain-java/langchain-core/index.html
<img width="1615" alt="image" src="https://github.com/HamaWhiteGG/langchain-java/assets/97529774/d140ca61-7965-4213-beb2-e69beb5ad07f">

Can it meet your needs? @liuziw
