### ISSUE TITLE
请问支持接入本地开源模型吗？比如Baichuan-7b、ChatGLM-6b、ChatGLM2-6b等

### ISSUE THREAD

**Issue by mylzj** [HamaWhiteGG/langchain-java#123]
thakns

**Comment by HamaWhiteGG** [comment]
supported [ChatGLM2](https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-examples/src/main/java/com/hw/langchain/examples/llms/ChatGLMExample.java) and [Ollama](https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-examples/src/main/java/com/hw/langchain/examples/llms/OllamaExample.java)， Baichuan-7b is not

**Comment by mylzj** [comment]
请问ChatGLM2就是指包含了ChatGLM-6b、ChatGLM2-6b对吧？

**Comment by HamaWhiteGG** [comment]
I tested ChatGLM2-6b, and ChatGLM-6b is uncertain.

**Comment by mylzj** [comment]
thanks
