### ISSUE TITLE
ZeroShotAgent与ChatAgent的 fromLlmAndTools方法名错误

### ISSUE THREAD

**Issue by yjy910323** [HamaWhiteGG/langchain-java#128]
方法名正确应该是fromLLMAndTools

agentObj = (BaseSingleActionAgent) MethodUtils.invokeStaticMethod(clazz, "fromLLMAndTools",
                    llm, tools, agentKwargs);

**Comment by HamaWhiteGG** [comment]
thanks, I fixed it
