### ISSUE TITLE
openai callback

### ISSUE THREAD

**Issue by stoneLee81** [HamaWhiteGG/langchain-java#17]
我从向量数据库根据query拿到了similarity_search的文档，我想通过类似langchain的这样函数，
with get_openai_callback() as cb:
    print(chain.run(input_documents=docs, question=query))
    print(cb)
传递给openai的大模型，这个可以在这个项目实现么？

**Comment by HamaWhiteGG** [comment]
Callback is not supported at the moment.

**Comment by fmatar** [comment]
Is there a plan to do it?

**Comment by HamaWhiteGG** [comment]
Yes, I will implement it next month.
