### ISSUE TITLE
[Question] - It looks like a proxy is needed everytime

### ISSUE THREAD

**Issue by clun** [HamaWhiteGG/langchain-java#2]
When initializing without providing any proxy (I do not need one) 

```
@Bean
public OpenAI llm() {
  return OpenAI.builder()
                .openaiApiKey(openAiKey)
                .openaiProxy("")
                .temperature(0.9f)
                .build()
                .init();
}
```

i got the error:
```
Did not find OPENAI_PROXY, please add an environment variable `OPENAI_PROXY` which contains it, or pass `OPENAI_PROXY` as a named parameter.
	at com.hw.langchain.utils.Utils.getFromEnv(Utils.java:72)
```

I seems the parameter is totally required: 
https://github.com/HamaWhiteGG/langchain-java/blob/main/openai-client/src/main/java/com/hw/openai/OpenAiClient.java#LL71C1-L71C1

**Comment by fmatar** [comment]
Yup, that's a bug, had the same issue

**Comment by HamaWhiteGG** [comment]
@clun @fmatar Thank you for reporting the bug. I have fixed it by adding a default value of "".

https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-core/src/main/java/com/hw/langchain/llms/openai/OpenAI.java#L45
```java
openaiProxy = Utils.getOrEnvOrDefault(openaiProxy, "OPENAI_PROXY","");
```
