### ISSUE TITLE
Can the project support file loader such as DirectoryLoader

### ISSUE THREAD

**Issue by hdblocal** [HamaWhiteGG/langchain-java#24]
Can the project support file loader such as DirectoryLoader

**Comment by HamaWhiteGG** [comment]
I added DirectoryLoader and NotionDirectoryLoader. Here are their unit test cases. Can you review them to see if they meet the requirements?

[DirectoryLoaderTest](https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-core/src/test/java/com/hw/langchain/document/loaders/directory/DirectoryLoaderTest.java)
```java
@Test
void testLoad() {
    String path = "../docs/extras/modules/";

    var loader = DirectoryLoader.builder()
            .path(Path.of(path))
            .loaderCls(TextLoader.class)
            .build();

    var docs = loader.load();
    assertEquals(1, docs.size());
}
```

[NotionDirectoryLoaderTest](https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-core/src/test/java/com/hw/langchain/document/loaders/notion/NotionDirectoryLoaderTest.java)
```java
@Test
void testLoad() {
    String path = "../docs/extras/use_cases/question_answering/notion_db/";

    var loader = new NotionDirectoryLoader(path);
    var docs = loader.load();
    assertEquals(1, docs.size());
    var mdFile = docs.get(0).getPageContent();
    assertNotNull(mdFile);
}
```
