### ISSUE TITLE
Azure OpenAI endpoint support

### ISSUE THREAD

**Issue by liorhar** [HamaWhiteGG/langchain-java#33]
Can Azure endpoint be used instead of OpenAI? How do I configure the endpoint/model/deployment/version that is needed on the Azure endpoint?

**Comment by dudu-upstream** [comment]
Waiting for that support too.

**Comment by gajendravaradhan** [comment]
Waiting for this too. Will there be support for Azure OpenAI?

**Comment by wangtl** [comment]
Waiting too.

**Comment by HamaWhiteGG** [comment]
thanks for your contribution @wangtl
