### ISSUE TITLE
Setting timeouts 

### ISSUE THREAD

**Issue by tckb** [HamaWhiteGG/langchain-java#6]
Hey.. thanks for writing this library. It works perfect for my usecase. however I use gpt-4 for my queries and 99% of my requests timeout, because the requests take a bit longer than 10 secs.  There doesn't seem to be  a way to increase the timeout. An environment variable to setup this param would be perfect. 

Thank you.

**Comment by HamaWhiteGG** [comment]
I'm glad you're using this project. I have added a parameter requestTimeout with a default value of 10 seconds. When constructing an OpenAiClient, you can set this parameter according to your needs.

[OpenAITest#testOpenAICall()](https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-core/src/test/java/com/hw/langchain/llms/openai/OpenAITest.java#LL37C28-L37C28)
```java
@Test
void testOpenAICall() {
    OpenAI llm = OpenAI.builder()
            .maxTokens(16)
            .requestTimeout(15)
            .build()
            .init();

    assertThat(llm.call("Say foo:")).isEqualTo("\n\nFoo!");
}
```

If you still need environment variables, we can continue the discussion.

**Comment by tckb** [comment]
Hey @HamaWhiteGG  thank you! I have a workaround exactly this :) with this config, I do not need any additional environment variable.

**Comment by HamaWhiteGG** [comment]
Thanks again!
