### ISSUE TITLE
UncrecognizedPropertyException in CompetionRes

### ISSUE THREAD

**Issue by robertmaj90** [HamaWhiteGG/langchain-java#64]
When running RetrievalQaExample there is an error like:
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"warning\" (class com.hw.openai.entity.completions.CompletionResp), not marked as ignorable

**Comment by HamaWhiteGG** [comment]
@wangmiao-1981 fixed it  #66

**Comment by HamaWhiteGG** [comment]
@robertmaj90  I add `objectMapper.configure(FAIL_ON_UNKNOWN_PROPERTIES, false)` for OpenAiClient to ignore unknown fields, for example the `warning ` field.
