### ISSUE TITLE
pls help me！！！！A 400 exception occurred while transferring data to pinecone          Exception in thread "main" retrofit2.adapter.rxjava2.HttpException: HTTP 400 

### ISSUE THREAD

**Issue by 2662007798** [HamaWhiteGG/langchain-java#73]
// upsert to Pinecone       
var response = index.upsert(new UpsertRequest(vectors, namespace));   
 In this line of code, I have an anomaly of 400.

  var client = PineconeClient.builder().pineconeApiKey("").pineconeEnv("").projectName("").requestTimeout(30).build().init();
  createPineconeIndex(client);

I have set these. What is the problem?  pls help me

**Comment by HamaWhiteGG** [comment]
Please provide the complete error information, as well as the code you were running.

**Comment by 2662007798** [comment]
> Please provide the complete error information, as well as the code you were running.

Connected to the target VM, address: '127.0.0.1:58936', transport: 'socket'
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.m2/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.m2/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-08-08 10:35:27 org.nd4j.linalg.factory.Nd4jBackend load 
INFO: Loaded [CpuBackend] backend
2023-08-08 10:35:28 org.nd4j.nativeblas.NativeOpsHolder initOps 
INFO: Number of threads used for linear algebra: 8
2023-08-08 10:35:28 org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory createBlas 
INFO: Binary level Generic x86 optimization level AVX/AVX2
2023-08-08 10:35:28 org.nd4j.nativeblas.Nd4jBlas <init> 
INFO: Number of threads used for OpenMP BLAS: 8
2023-08-08 10:35:28 org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation 
INFO: Backend used: [CPU]; OS: [Windows 10]
2023-08-08 10:35:28 org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation 
INFO: Cores: [8]; Memory: [8.0GB];
2023-08-08 10:35:28 org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation 
INFO: Blas vendor: [OPENBLAS]
2023-08-08 10:35:28 org.nd4j.linalg.cpu.nativecpu.CpuBackend logBackendInit 
INFO: Backend build information:
 GCC: "12.1.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS
Exception in thread "main" retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2517)
	at io.reactivex.Single.blockingGet(Single.java:2001)
	at com.hw.pinecone.IndexClient.upsert(IndexClient.java:76)
	at com.hw.langchain.vectorstores.pinecone.Pinecone.fromTexts(Pinecone.java:207)
	at com.hw.langchain.vectorstores.base.VectorStore.fromDocuments(VectorStore.java:195)
	at com.hw.langchain.examples.vectorstores.PineconeExample.initializePineconeIndex(PineconeExample.java:69)
	at com.hw.langchain.examples.chains.RetrievalQaExample.main(RetrievalQaExample.java:51)
Disconnected from the target VM, address: '127.0.0.1:58936', transport: 'socket'

**Comment by 2662007798** [comment]
com.hw.langchain.vectorstores.pinecone.Pinecone 207line Mistake of

**Comment by HamaWhiteGG** [comment]
Sorry for the delay in my response. I've been busy with work. 

I've added the [log4j.properties](https://github.com/HamaWhiteGG/langchain-java/blob/dev/langchain-examples/src/main/resources/log4j.properties) file and resolved the package conflict issue in the langchain-example directory. 

The default level is set to INFO, but you can change it to DEBUG to view more detailed logs.

```
log4j.rootLogger=DEBUG, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d %5p %t %-20c.%M:%L - %m%n
```

**Comment by HamaWhiteGG** [comment]
Has your problem been resolved?

**Comment by 2662007798** [comment]
> Has your problem been resolved?

It hasn't been solved yet, and it's still the same problem at present.




C:\Users\Administrator\.jdks\jbrsdk_jcef-17.0.7\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.3\lib\idea_rt.jar=55169:C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.3\bin" -Dfile.encoding=UTF-8 -classpath F:\work\java-langchain\langchain-java-main\langchain-examples\target\classes;F:\work\java-langchain\langchain-java-main\langchain-core\target\classes;F:\work\java-langchain\langchain-java-main\openai-client\target\classes;C:\Users\Administrator\.m2\com\squareup\retrofit2\retrofit\2.9.0\retrofit-2.9.0.jar;C:\Users\Administrator\.m2\com\squareup\retrofit2\adapter-rxjava2\2.9.0\adapter-rxjava2-2.9.0.jar;C:\Users\Administrator\.m2\io\reactivex\rxjava2\rxjava\2.0.0\rxjava-2.0.0.jar;C:\Users\Administrator\.m2\com\squareup\retrofit2\converter-jackson\2.9.0\converter-jackson-2.9.0.jar;C:\Users\Administrator\.m2\com\squareup\okhttp3\logging-interceptor\3.14.9\logging-interceptor-3.14.9.jar;C:\Users\Administrator\.m2\com\fasterxml\jackson\core\jackson-annotations\2.15.1\jackson-annotations-2.15.1.jar;C:\Users\Administrator\.m2\org\hibernate\validator\hibernate-validator\8.0.0.Final\hibernate-validator-8.0.0.Final.jar;C:\Users\Administrator\.m2\jakarta\validation\jakarta.validation-api\3.0.2\jakarta.validation-api-3.0.2.jar;C:\Users\Administrator\.m2\org\jboss\logging\jboss-logging\3.4.1.Final\jboss-logging-3.4.1.Final.jar;C:\Users\Administrator\.m2\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;F:\work\java-langchain\langchain-java-main\serpapi-client\target\classes;C:\Users\Administrator\.m2\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;F:\work\java-langchain\langchain-java-main\pinecone-client\target\classes;C:\Users\Administrator\.m2\io\milvus\milvus-sdk-java\2.2.9\milvus-sdk-java-2.2.9.jar;C:\Users\Administrator\.m2\io\grpc\grpc-netty-shaded\1.46.0\grpc-netty-shaded-1.46.0.jar;C:\Users\Administrator\.m2\io\perfmark\perfmark-api\0.25.0\perfmark-api-0.25.0.jar;C:\Users\Administrator\.m2\io\grpc\grpc-core\1.46.0\grpc-core-1.46.0.jar;C:\Users\Administrator\.m2\com\google\android\annotations\4.1.1.4\annotations-4.1.1.4.jar;C:\Users\Administrator\.m2\org\codehaus\mojo\animal-sniffer-annotations\1.19\animal-sniffer-annotations-1.19.jar;C:\Users\Administrator\.m2\io\grpc\grpc-protobuf\1.46.0\grpc-protobuf-1.46.0.jar;C:\Users\Administrator\.m2\io\grpc\grpc-api\1.46.0\grpc-api-1.46.0.jar;C:\Users\Administrator\.m2\io\grpc\grpc-context\1.46.0\grpc-context-1.46.0.jar;C:\Users\Administrator\.m2\com\google\api\grpc\proto-google-common-protos\2.0.1\proto-google-common-protos-2.0.1.jar;C:\Users\Administrator\.m2\io\grpc\grpc-protobuf-lite\1.46.0\grpc-protobuf-lite-1.46.0.jar;C:\Users\Administrator\.m2\io\grpc\grpc-stub\1.46.0\grpc-stub-1.46.0.jar;C:\Users\Administrator\.m2\com\google\protobuf\protobuf-java\3.19.6\protobuf-java-3.19.6.jar;C:\Users\Administrator\.m2\com\fasterxml\jackson\core\jackson-databind\2.12.7.1\jackson-databind-2.12.7.1.jar;C:\Users\Administrator\.m2\com\squareup\okhttp3\okhttp\4.9.2\okhttp-4.9.2.jar;C:\Users\Administrator\.m2\com\squareup\okio\okio\2.8.0\okio-2.8.0.jar;C:\Users\Administrator\.m2\org\codehaus\plexus\plexus-utils\3.0.20\plexus-utils-3.0.20.jar;C:\Users\Administrator\.m2\org\jetbrains\kotlin\kotlin-stdlib\1.6.0\kotlin-stdlib-1.6.0.jar;C:\Users\Administrator\.m2\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\Administrator\.m2\org\jetbrains\kotlin\kotlin-stdlib-common\1.6.0\kotlin-stdlib-common-1.6.0.jar;C:\Users\Administrator\.m2\com\alibaba\fastjson\1.2.76\fastjson-1.2.76.jar;C:\Users\Administrator\.m2\com\google\guava\guava\32.0.1-jre\guava-32.0.1-jre.jar;C:\Users\Administrator\.m2\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\Administrator\.m2\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Administrator\.m2\org\checkerframework\checker-qual\3.33.0\checker-qual-3.33.0.jar;C:\Users\Administrator\.m2\com\google\errorprone\error_prone_annotations\2.18.0\error_prone_annotations-2.18.0.jar;C:\Users\Administrator\.m2\com\google\j2objc\j2objc-annotations\2.8\j2objc-annotations-2.8.jar;C:\Users\Administrator\.m2\org\apache\commons\commons-text\1.10.0\commons-text-1.10.0.jar;C:\Users\Administrator\.m2\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\Administrator\.m2\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native-platform\1.0.0-M2.1\nd4j-native-platform-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas-platform\0.3.19-1.5.7\openblas-platform-0.3.19-1.5.7.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp-platform\1.5.7\javacpp-platform-1.5.7.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-android-arm.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-android-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-android-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-android-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-ios-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-ios-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-linux-armhf.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-linux-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-linux-ppc64le.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-linux-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-linux-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-macosx-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-macosx-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-windows-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-android-arm.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-android-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-android-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-android-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-ios-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-ios-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-linux-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-linux-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-linux-armhf.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-linux-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-linux-ppc64le.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-macosx-arm64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-macosx-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-windows-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\openblas\0.3.19-1.5.7\openblas-0.3.19-1.5.7-windows-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl-platform\2022.0-1.5.7\mkl-platform-2022.0-1.5.7.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl\2022.0-1.5.7\mkl-2022.0-1.5.7.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl\2022.0-1.5.7\mkl-2022.0-1.5.7-linux-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl\2022.0-1.5.7\mkl-2022.0-1.5.7-linux-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl\2022.0-1.5.7\mkl-2022.0-1.5.7-macosx-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl\2022.0-1.5.7\mkl-2022.0-1.5.7-windows-x86.jar;C:\Users\Administrator\.m2\org\bytedeco\mkl\2022.0-1.5.7\mkl-2022.0-1.5.7-windows-x86_64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-api\1.0.0-M2.1\nd4j-api-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\com\jakewharton\byteunits\byteunits\0.9.1\byteunits-0.9.1.jar;C:\Users\Administrator\.m2\org\apache\commons\commons-math3\3.5\commons-math3-3.5.jar;C:\Users\Administrator\.m2\com\google\flatbuffers\flatbuffers-java\1.12.0\flatbuffers-java-1.12.0.jar;C:\Users\Administrator\.m2\org\nd4j\protobuf\1.0.0-M2.1\protobuf-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\com\github\oshi\oshi-core\3.4.2\oshi-core-3.4.2.jar;C:\Users\Administrator\.m2\net\java\dev\jna\jna-platform\4.3.0\jna-platform-4.3.0.jar;C:\Users\Administrator\.m2\net\java\dev\jna\jna\4.3.0\jna-4.3.0.jar;C:\Users\Administrator\.m2\org\threeten\threetenbp\1.3.3\threetenbp-1.3.3.jar;C:\Users\Administrator\.m2\org\nd4j\jackson\1.0.0-M2.1\jackson-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\commons-net\commons-net\3.1\commons-net-3.1.jar;C:\Users\Administrator\.m2\net\ericaro\neoitertools\1.0.0\neoitertools-1.0.0.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-common\1.0.0-M2.1\nd4j-common-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\org\nd4j\guava\1.0.0-M2.1\guava-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\commons-io\commons-io\2.7\commons-io-2.7.jar;C:\Users\Administrator\.m2\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\Administrator\.m2\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native-api\1.0.0-M2.1\nd4j-native-api-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native-preset\1.0.0-M2.1\nd4j-native-preset-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-presets-common\1.0.0-M2.1\nd4j-presets-common-1.0.0-M2.1.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native-preset\1.0.0-M2.1\nd4j-native-preset-1.0.0-M2.1-windows-x86_64.jar;C:\Users\Administrator\.m2\org\bytedeco\javacpp\1.5.7\javacpp-1.5.7-windows-x86_64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-android-arm.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-android-arm64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-android-x86.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-android-x86_64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-linux-x86_64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-macosx-x86_64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-windows-x86_64.jar;C:\Users\Administrator\.m2\org\nd4j\nd4j-native\1.0.0-M2.1\nd4j-native-1.0.0-M2.1-linux-armhf.jar;C:\Users\Administrator\.m2\org\python\jython-standalone\2.7.3\jython-standalone-2.7.3.jar;C:\Users\Administrator\.m2\com\knuddels\jtokkit\0.5.0\jtokkit-0.5.0.jar;C:\Users\Administrator\.m2\org\slf4j\slf4j-api\1.7.32\slf4j-api-1.7.32.jar;C:\Users\Administrator\.m2\org\slf4j\slf4j-log4j12\1.7.25\slf4j-log4j12-1.7.25.jar;C:\Users\Administrator\.m2\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Administrator\.m2\com\mysql\mysql-connector-j\8.0.32\mysql-connector-j-8.0.32.jar;C:\Users\Administrator\.m2\org\redisson\redisson\3.17.3\redisson-3.17.3.jar;C:\Users\Administrator\.m2\io\netty\netty-common\4.1.77.Final\netty-common-4.1.77.Final.jar;C:\Users\Administrator\.m2\io\netty\netty-codec\4.1.77.Final\netty-codec-4.1.77.Final.jar;C:\Users\Administrator\.m2\io\netty\netty-buffer\4.1.77.Final\netty-buffer-4.1.77.Final.jar;C:\Users\Administrator\.m2\io\netty\netty-transport\4.1.77.Final\netty-transport-4.1.77.Final.jar;C:\Users\Administrator\.m2\io\netty\netty-handler\4.1.77.Final\netty-handler-4.1.77.Final.jar;C:\Users\Administrator\.m2\javax\cache\cache-api\1.1.1\cache-api-1.1.1.jar;C:\Users\Administrator\.m2\io\projectreactor\reactor-core\3.4.13\reactor-core-3.4.13.jar;C:\Users\Administrator\.m2\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\Administrator\.m2\io\reactivex\rxjava3\rxjava\3.0.12\rxjava-3.0.12.jar;C:\Users\Administrator\.m2\org\jboss\marshalling\jboss-marshalling\2.0.11.Final\jboss-marshalling-2.0.11.Final.jar;C:\Users\Administrator\.m2\org\jboss\marshalling\jboss-marshalling-river\2.0.11.Final\jboss-marshalling-river-2.0.11.Final.jar;C:\Users\Administrator\.m2\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.13.2\jackson-dataformat-yaml-2.13.2.jar;C:\Users\Administrator\.m2\org\yaml\snakeyaml\1.30\snakeyaml-1.30.jar;C:\Users\Administrator\.m2\com\fasterxml\jackson\core\jackson-core\2.13.2\jackson-core-2.13.2.jar;C:\Users\Administrator\.m2\net\bytebuddy\byte-buddy\1.11.0\byte-buddy-1.11.0.jar;C:\Users\Administrator\.m2\org\jodd\jodd-bean\5.1.6\jodd-bean-5.1.6.jar;C:\Users\Administrator\.m2\org\jodd\jodd-core\5.1.6\jodd-core-5.1.6.jar;C:\Users\Administrator\.m2\io\netty\netty-resolver\4.1.43.Final\netty-resolver-4.1.43.Final.jar;C:\Users\Administrator\.m2\io\netty\netty-resolver-dns\4.1.43.Final\netty-resolver-dns-4.1.43.Final.jar;C:\Users\Administrator\.m2\io\netty\netty-codec-dns\4.1.43.Final\netty-codec-dns-4.1.43.Final.jar;C:\Users\Administrator\.m2\org\reflections\reflections\0.10.2\reflections-0.10.2.jar;C:\Users\Administrator\.m2\org\javassist\javassist\3.28.0-GA\javassist-3.28.0-GA.jar;C:\Users\Administrator\.m2\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Administrator\.m2\org\awaitility\awaitility\4.2.0\awaitility-4.2.0.jar;C:\Users\Administrator\.m2\org\hamcrest\hamcrest\2.1\hamcrest-2.1.jar com.hw.langchain.examples.chains.RetrievalQaExample
2023-08-14 10:59:18,154  INFO main org.nd4j.linalg.factory.Nd4jBackend.load:193 - Loaded [CpuBackend] backend
2023-08-14 10:59:19,155  INFO main org.nd4j.nativeblas.NativeOpsHolder.initOps:155 - Number of threads used for linear algebra: 8
2023-08-14 10:59:19,158  INFO main org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas:103 - Binary level Generic x86 optimization level AVX/AVX2
2023-08-14 10:59:19,174  INFO main org.nd4j.nativeblas.Nd4jBlas.<init>:55 - Number of threads used for OpenMP BLAS: 8
2023-08-14 10:59:19,188  INFO main org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation:673 - Backend used: [CPU]; OS: [Windows 10]
2023-08-14 10:59:19,188  INFO main org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation:674 - Cores: [8]; Memory: [8.0GB];
2023-08-14 10:59:19,188  INFO main org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation:675 - Blas vendor: [OPENBLAS]
2023-08-14 10:59:19,192  INFO main org.nd4j.linalg.cpu.nativecpu.CpuBackend.logBackendInit:84 - Backend build information:
 GCC: "12.1.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU

023-08-14 11:02:04,696 DEBUG main com.hw.pinecone.PineconeClient.intercept:211 - --> END POST (654274-byte body)
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.intercept:233 - <-- 400 https://langchain-demo-1f79cca.svc.us-west4-gcp-free.pinecone.io/vectors/upsert (994ms)
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.logHeader:294 - content-type: application/json
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.logHeader:294 - date: Mon, 14 Aug 2023 03:02:05 GMT
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.logHeader:294 - x-envoy-upstream-service-time: 2
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.logHeader:294 - content-length: 104
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.logHeader:294 - server: envoy
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.intercept:276 - 
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.intercept:277 - {"code":3,"message":"Vector dimension 1536 does not match the dimension of the index 1024","details":[]}
2023-08-14 11:02:05,692 DEBUG main com.hw.pinecone.PineconeClient.intercept:284 - <-- END HTTP (104-byte body)


HAVE_FLATBUFFERS
HAVE_OPENBLAS
Exception in thread "main" retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2517)
	at io.reactivex.Single.blockingGet(Single.java:2001)
	at com.hw.pinecone.IndexClient.upsert(IndexClient.java:76)
	at com.hw.langchain.vectorstores.pinecone.Pinecone.fromTexts(Pinecone.java:207)
	at com.hw.langchain.vectorstores.base.VectorStore.fromDocuments(VectorStore.java:195)
	at com.hw.langchain.examples.vectorstores.PineconeExample.initializePineconeIndex(PineconeExample.java:69)
	at com.hw.langchain.examples.chains.RetrievalQaExample.main(RetrievalQaExample.java:51)

Process finished with exit code 1

**Comment by 2662007798** [comment]
> Has your problem been resolved?



> Has your problem been resolved?

Thank you very much, I have solved this problem, the current problem through log4j, found to be the Pinecone index library length problem, set to 1536 can be solved very much!!!!!!

**Comment by HamaWhiteGG** [comment]
Welcome to contribute code to this project.
