### ISSUE TITLE
how to support other open source model，such as glm/llama2 etc.

### ISSUE THREAD

**Issue by lubibama** [HamaWhiteGG/langchain-java#74]
how to support other open source model，such as glm/llama2 etc. do you have this plan

**Comment by kael-aiur** [comment]
you can implement BaseLLM or BaseChatModel by your self

**Comment by HamaWhiteGG** [comment]
@lubibama Sorry, I don't have the environment for glm and llama2, which prevents me from testing. Can I check if ollama meets your requirements?

https://github.com/jmorganca/ollama

**Comment by HamaWhiteGG** [comment]
I now support Ollama2, you can see [OllamaExample](https://github.com/HamaWhiteGG/langchain-java/blob/dev/langchain-examples/src/main/java/com/hw/langchain/examples/llms/OllamaExample.java#L30)

```java
public static void main(String[] args) {
    var llm = Ollama.builder()
            .baseUrl("http://localhost:11434")
            .model("llama2")
            .temperature(0f)
            .build()
            .init();

    var result = llm.predict("What is the capital of China?");

    // The capital of China is Beijing.
    println(result);
}
```
