### ISSUE TITLE
如何解决tokens超过限制的问题呢？

### ISSUE THREAD

**Issue by leavestyle-coder** [HamaWhiteGG/langchain-java#80]
我想使用langchain + graphQl 来做问答，当Graph的数据节点比较多时，langchain调openAI的prompt就会太长，接口报了超出tokens限制，这种有什么好的解决方式吗？

**Comment by HamaWhiteGG** [comment]
I don't have a good idea yet, but you can take a look at [Embedding texts that are longer than the model's maximum context length](https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb) to see if it's helpful for you.

The code in langchain-java is [OpenAIEmbeddings#getLenSafeEmbeddings](https://github.com/HamaWhiteGG/langchain-java/blob/main/langchain-core/src/main/java/com/hw/langchain/embeddings/openai/OpenAIEmbeddings.java#L122)
